### ISSUE TITLE
not able to reproduce the results

### ISSUE THREAD

**Issue by ramonsanabria** [dialogtekgeek/AudioVisualSceneAwareDialog#2]
Hi,

I just run the code provided and I am not able to reproduce the results. I am getting the following:

  name | bleu_1 | bleu_2 | bleu_3 | bleu_4 | meteor | rouger_l | cider
baseline (i3d_rgb,i3d_flow) | 0.247 | 0.161 | 0.112 | 0.081 | 0.096 | 0.227 | 0.648
baseline (i3d_rgb,i3d_flow,vggish) | 0.251 | 0.164 | 0.116 | 0.084 | 0.095 | 0.23 | 0.666

Thoughts?

Thanks!

**Comment by ramonsanabria** [comment]
sorry this is solved. I was not using the correct test labels.

**Comment by AmingWu** [comment]
@ramonsanabria， Could you show your final results of this method?
